
import React, { useState } from 'react';
import { Mail, Lock, User as UserIcon, ArrowLeft, AlertCircle, Loader2, Database, Copy, CheckCircle } from 'lucide-react';
import { db } from '../services/db';
import { User } from '../types';

interface RegisterProps {
  onToggleAuth: () => void;
  onBackHome: () => void;
  onSuccess: (user: User) => void;
}

const Register: React.FC<RegisterProps> = ({ onToggleAuth, onBackHome, onSuccess }) => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [showSetupGuide, setShowSetupGuide] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setShowSetupGuide(false);

    if (!name || !email || !password) {
      setError('Please fill in all fields.');
      return;
    }

    setLoading(true);
    try {
      const existing = await db.findUserByEmail(email);
      if (existing) {
        setError('This email is already registered.');
        setLoading(false);
        return;
      }

      const newUser: User = {
        id: Math.random().toString(36).substr(2, 9),
        name,
        email,
        password,
        createdAt: new Date().toISOString()
      };

      await db.saveUser(newUser);
      db.setCurrentUser(newUser);
      onSuccess(newUser);
    } catch (err: any) {
      console.error("Signup process failed:", err);
      
      if (err.message.includes("RLS_ERROR") || err.message.includes("TABLE_MISSING")) {
        setError(err.message.includes("RLS_ERROR") 
          ? "Database security policy is blocking signup." 
          : "Database tables have not been created.");
        setShowSetupGuide(true);
      } else {
        setError(err.message || 'Connection error. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  const sqlSetup = `-- 1. Create Tables
CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item TEXT NOT NULL,
  category TEXT NOT NULL,
  confidence FLOAT NOT NULL,
  instructions TEXT NOT NULL,
  user_id TEXT REFERENCES public.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Disable Security (RLS) to allow the app to work
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.scans DISABLE ROW LEVEL SECURITY;`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlSetup);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-[80vh] flex items-center justify-center px-4 py-12">
      <div className="max-w-md w-full">
        <button 
          onClick={onBackHome}
          className="flex items-center text-gray-400 hover:text-white transition-colors mb-8 group"
        >
          <ArrowLeft className="w-4 h-4 mr-2 group-hover:-translate-x-1 transition-transform" />
          Back to Home
        </button>
        
        <div className="bg-gray-900 border border-gray-800 rounded-[40px] p-8 shadow-2xl relative overflow-hidden">
          <div className="text-center mb-10">
            <h2 className="text-3xl font-bold mb-2">Create Account</h2>
            <p className="text-gray-400">Join the waste management revolution</p>
          </div>

          {error && (
            <div className="mb-6 p-4 bg-red-500/10 border border-red-500/20 rounded-2xl flex items-start text-red-400 text-sm animate-in fade-in slide-in-from-top-2">
              <AlertCircle className="w-4 h-4 mr-2 shrink-0 mt-0.5" />
              <div>
                <p className="font-bold">Database Configuration Error</p>
                <p className="opacity-80">{error}</p>
              </div>
            </div>
          )}

          {showSetupGuide && (
            <div className="mb-8 bg-blue-600/10 border border-blue-500/30 rounded-2xl p-6 text-sm animate-in zoom-in-95 duration-300">
              <div className="flex items-center text-blue-400 font-bold mb-4">
                <Database className="w-5 h-5 mr-2" />
                Quick Setup Required
              </div>
              <ol className="list-decimal list-inside text-gray-400 space-y-3 mb-6 leading-relaxed">
                <li>Go to your <a href="https://supabase.com/dashboard" target="_blank" className="text-blue-400 hover:underline">Supabase SQL Editor</a></li>
                <li>Copy the code block below</li>
                <li>Paste it and click <strong>Run</strong></li>
                <li>Try signing up again!</li>
              </ol>
              
              <div className="relative group">
                <pre className="bg-black/40 p-4 rounded-xl text-[10px] text-green-500 font-mono overflow-x-auto border border-gray-800 max-h-48">
                  {sqlSetup}
                </pre>
                <button 
                  onClick={copyToClipboard}
                  className="absolute top-2 right-2 p-2 bg-gray-800 rounded-lg hover:bg-gray-700 text-gray-300 transition-colors flex items-center"
                >
                  {copied ? <CheckCircle className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                  <span className="ml-2 text-[10px] font-bold">{copied ? 'Copied!' : 'Copy SQL'}</span>
                </button>
              </div>
            </div>
          )}
          
          <form className="space-y-6" onSubmit={handleSubmit}>
            <div>
              <label className="block text-sm font-medium text-gray-400 mb-2">Full Name</label>
              <div className="relative">
                <UserIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500" />
                <input 
                  type="text" 
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="Jane Doe"
                  disabled={loading}
                  className="w-full bg-gray-800/50 border border-gray-700 rounded-xl py-3 pl-10 pr-4 focus:outline-none focus:border-green-500 transition-colors disabled:opacity-50"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-400 mb-2">Email Address</label>
              <div className="relative">
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500" />
                <input 
                  type="email" 
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="name@example.com"
                  disabled={loading}
                  className="w-full bg-gray-800/50 border border-gray-700 rounded-xl py-3 pl-10 pr-4 focus:outline-none focus:border-green-500 transition-colors disabled:opacity-50"
                />
              </div>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-400 mb-2">Password</label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500" />
                <input 
                  type="password" 
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Min. 6 characters"
                  disabled={loading}
                  className="w-full bg-gray-800/50 border border-gray-700 rounded-xl py-3 pl-10 pr-4 focus:outline-none focus:border-green-500 transition-colors disabled:opacity-50"
                />
              </div>
            </div>
            
            <button 
              type="submit" 
              disabled={loading}
              className="w-full bg-green-600 hover:bg-green-500 text-white py-3.5 rounded-xl font-bold transition-all shadow-xl shadow-green-900/20 flex items-center justify-center disabled:opacity-50"
            >
              {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : 'Create Account'}
            </button>
          </form>
          
          <p className="mt-10 text-center text-gray-400 text-sm border-t border-gray-800 pt-8">
            Already have an account?{' '}
            <button onClick={onToggleAuth} className="text-green-500 font-bold hover:underline">
              Sign In
            </button>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Register;
